apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-1
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: helm
    repoURL: https://github.com/yoelpg/argocd-demo1
    targetRevision: HEAD
    helm:
      values: |
        image:
          repository: vfarcic/devops-toolkit
          tag: latest
      version: v3
  destination:
    namespace: production
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
